name: Promote to Staging

on:
  workflow_call:
    inputs:
      cr_number:
        description: "CR Number"
        required: true
        type: string
      release_branch_name:
        description: "Release branch to promote (e.g. release/release-name)"
        required: true
        type: string

jobs:
  checks-and-informations:
    runs-on: ubuntu-latest
    steps:
      - name: Branch Check
        run: |
          if [[ ${{ github.ref_name }} = main*  ]]
          then
            echo "${{ github.ref_name }} branch is allowed"
          else
            echo "${{ github.ref_name }} branch is not allowed"
            exit 1
          fi
        shell: bash
      - name: CR Information
        run: |
          echo "🚀 Staging Promotion Request"
          echo "CR Number: ${{ inputs.cr_number }}"
          echo "Release Branch Name: ${{ inputs.release_branch_name }}"
        shell: bash

  approve_security:
    runs-on: ubuntu-latest
    needs: checks-and-informations
    environment: stg-approve-security
    steps:
      - run: echo "Security approval granted."

  approve_release:
    runs-on: ubuntu-latest
    needs: approve_security
    environment: stg-approve-po
    steps:
      - run: echo "Release/Change approval granted."

  stg-deployment:
    runs-on: ubuntu-latest
    needs: approve_release
    environment: stg
    steps:
      - name: Validate CR number
        run: |
          if [ -z "${{ inputs.cr_number }}" ]; then
            echo "CR number is required."
            exit 1
          fi
          echo "CR=${{ inputs.cr_number }}"

      - name: Checkout config repo
        uses: actions/checkout@master
        with:
          repository: ${{ github.repository }}-config
          ref: staging
          path: './${{ github.event.repository.name }}-config'

      - name: Update values-stg.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          repository: ${{ github.repository }}-config
          workDir: '${{ github.event.repository.name }}-config'
          valueFile: 'helm-charts/${{ github.event.repository.name }}/values-stg.yaml'
          propertyPath: 'image.tag'
          value: ${{ inputs.release_branch_name }}
          branch: staging
          masterBranchName: staging
          targetBranch: staging
          token: ${{ secrets.CONFIG_PAT }}
          message: CD Change by Pipeline - CR=${{ inputs.cr_number }}
          commitChange: true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Retag image as STG
        run: |
          docker pull canpolatoral/${{ github.event.repository.name }}:${{ inputs.release_branch_name }}
          docker tag  canpolatoral/${{ github.event.repository.name }}:${{ inputs.release_branch_name }} \
                     canpolatoral/${{ github.event.repository.name }}:stg-latest
          docker push canpolatoral/${{ github.event.repository.name }}:stg-latest
